# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      nombres: Renzo José
      apellidos: Garavito Valdivia
      edad: "22"
      version_de_mi_proyecto: "3.0"
      user: ${{secrets.USER}}
      password: ${{secrets.PASSWORD}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Creacion de Steps llamado Presentacion
      - name: Presentacion
        run: |
          echo "Nombres: $nombres"
          echo "Apellidos: $apellidos"
          echo "Edad: $edad años"
      
      # Step para los datos generales
      - name: Datos generales
        run: echo "carrera de ingeniería de sistemas"

      # Step para variables de entorno de usuario y contraseña
      - name: Mostrar variables de entorno secretas
        run: |
          echo "Usuario: ${{env.user}}"
          echo "Contraseña: ${{env.password}}"
      
      # Step para variable abierta 
      - name: Variable abierta
        run: |
          echo Variable abierta: ${{ vars.version_de_mi_proyecto }}
      
      # Step para variables abierta 
      - name: Variables abiertas 
        run: |
          echo "Version del proyecto: $version_de_mi_proyecto"
          echo "Nombres: $nombres"
          echo "Apellidos: $apellidos"
          echo "Edad: $edad"*"

